//  MAP function : conbination of data which is exits in key value players 


//  map is same like of set , the structure is also same , there is no diffrence between the structure 


//  in map we cannot delete the duplicate elements as in case of the sets 


//  in case of set the values are individual elements = array 

//  in case of map the values are key value players = object 


//  to initiaze map you have to use the new constructer function 




let a = new Map ()

// to add somthing in map you have to use set function and you have to give two values "ID" and "KEY"


a.set("id",5)       // key should be always a string 
console.log(a);

// to access the individual values use "GET FFUNVTION" and enter the key value of that 


console.log(a.get("id"));


//  we can also have size and has funcition in maps as same that of the sets 









